package com.fengjr.crm.model.db;

// Generated 2015-8-25 11:07:29 by Hibernate Tools 3.4.0.CR1

/**
 * UserPoints generated by hbm2java
 */
public class UserPoints implements java.io.Serializable {

    private String userId;
    private Integer totalPoints;
    private Integer upgradePoints;
    private Integer availablePoints;
    private String level;
    private String levelName;
    private String expiredTime;
    private String status;
    private String comments;
    private String permanentDiamondUser;
    private String createTime;
    private String updateTime;

    public UserPoints() {
    }

    public UserPoints(String userId) {
        this.userId = userId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getTotalPoints() {
        return this.totalPoints;
    }

    public void setTotalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
    }

    public Integer getUpgradePoints() {
        return this.upgradePoints;
    }

    public void setUpgradePoints(Integer upgradePoints) {
        this.upgradePoints = upgradePoints;
    }

    public Integer getAvailablePoints() {
        return this.availablePoints;
    }

    public void setAvailablePoints(Integer availablePoints) {
        this.availablePoints = availablePoints;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getLevelName() {
        return this.levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    public String getExpiredTime() {
        return this.expiredTime;
    }

    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getPermanentDiamondUser() {
        return permanentDiamondUser;
    }

    public void setPermanentDiamondUser(String permanentDiamondUser) {
        this.permanentDiamondUser = permanentDiamondUser;
    }
}
